---
title: "Trabalho Final MQ I"
author: "Davi Camargo"
date: "2026-07-15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Trabalho Final de Métodos Quantitativos e Técnicas de Pesquisa em Ciência Política I**

**Davi Ribeiro de Camargo - 12507199 - Pós-Graduação**

**INSTRUÇÕES INICIAIS**

Para a realização do trabalho, foi criado um repositório no GitHub, que pode ser consultado em: https://github.com/daviribeiro11drc/Trabalho_final_MQI.git

Executei os códigos sugeridos para utilização dos pacotes:

library(readxl)
library(dplyr)
library(ggplot2)

Por fim, transformei a aba "BASE_cargos" do banco de dados no objeto "dados":

dados <- read_excel("BASE_cargos2.xlsx", sheet = "BASE_cargos")

**PERGUNTAS OBRIGATÓRIAS**

**1. Artigo, pergunta e unidade de análise**

  *1.1- Qual é a pergunta geral do artigo?*

  *1.2- Qual é a unidade de análise da base?*

  *1.3- O que significa uma linha da base?*

  *1.4- Por que a mesma pessoa pode aparecer mais de uma vez?*

  *1.5- Quais são as duas pastas comparadas no artigo?*

**2. Leitura e validação dos dados**

  *2.1- Número de linhas e colunas.*